### PR TITLE
Add a simple favorites service. Power the favorites list by pets the user has expressed interest in

### PR DESCRIPTION
**Pull request by smacgregor**
@cbaja @scottrichards 

Issue #46 - keep track of skipped pets and remove skipped pets from a passed in list of pets
Issue #52 - when scrolling the favorites list view each row item suddenly takes a bunch of white space

A simple in memory service that keeps track of favorite and skipped pets. I updated the favorites fragment to be powered based on favorite pets. 

favorites

### CODE REVIEW

**Comment by smacgregor** [comment]
@scottrichards  - you can call 

```
FavoritesService.getInstance().removeSkippedPets(List<PetModel)
```

to remove pets the user has decided they aren't interested in from a set of pet models.

**Comment by scottrichards** [comment]
Looks good to me.

**Comment by scottrichards** [comment]
Looks like there are conflicts that need to be resolved...

**Comment by smacgregor** [comment]
looking into the conflicts now

**Comment by smacgregor** [comment]
@scottrichards - merge conflicts resolved against master. Can you merge this if it looks good to you? Thanks!

**Pull request closed without merging**
